from operations import *

TRAINING_DATA_FILE = "testData.csv"
TRAINING_DATA_LABEL = "label"
NEURAL_NETWORK_FILE = "trainedNet.csv"
PRETRAINED_NEURAL_NETWORK = True
SAVE_TO_FILE = "trainedNet.csv"


LOSS_FUNCTION = L2LossFunction
LEARNING_RATE = 0.0000000025
TRAINING_COMPLETE_THRESHOLD = 0.25
MAX_EPOCHS = 1000
