from operations import *

## Saving and Loading
TRAINING_DATA_FILE = "testData.csv"
TRAINING_DATA_LABEL = "f(x,y,z)"
NEURAL_NETWORK_FILE = "testNet.csv"
PRETRAINED_NEURAL_NETWORK = False
SAVE_TO_FILE = "trainedNet.csv"

## Training
LOSS_FUNCTION = L2LossFunction
LEARNING_RATE = 0.0000000000025
TRAINING_COMPLETE_THRESHOLD = 50
MAX_EPOCHS = 2000

## Data Generation
TRAINING_DATA_MAX_EXPONENT = 5
TRAINING_DATA_MULTIPLICATIVE_VARIANCE = 0
TRAINING_DATA_ADDITIVE_VARIANCE = 0